name: lendingclub
stage: Staging
mlflow_experiment_path: /Shared/dbx/leclub_db4ml_test2
modules:
  - lendingclubdb4ml.lendingclub


source_tables:
  lending_club_train_source:
    format: parquet
    path: dbfs:/databricks-datasets/samples/lending_club/parquet
  lending_club_stream:
    format: parquet
    path: dbfs:/databricks-datasets/samples/lending_club/parquet

models:
  lending_club_model:
    flavour: sklearn
    target_column: bad_loan
    test_size: 0.2
    params:
      - name: n_estimators
        default: 10
        search_space: "...."

pipelines:
  lendingclub_train:
    type: model_train
    train_options:
      model_name: lending_club_model
      train_dataset: lendingclub_dataset
      promote_in_registry: true
      initial_stage: Staging
    variables:
      - variable: source_df
        value: lending_club_train_source
    split: true

  lending_scoring_spark:
    type: spark_batch
    models:
      - model_name: lending_club_model
        model_selection: model_registry
    variables:
      - variable: source_df
        value: lending_club_stream
    params:
      format: parquet
      table_name: le_out1
  lending_scoring_pandas:
    type: spark_batch
    models:
      - model_name: lending_club_model
        model_selection: model_registry
    variables:
      - variable: source_df
        value: lending_club_stream
    params:
      format: parquet
      table_name: le_out2
